
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/snap/clion/282/bin/cmake/linux/x64/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Linux - 5.15.0-107-generic - x86_64
...
